[package]
name = "rb-node-rpc-client"
version = "2.0.0"
authors = ["Damian Straszak <damian.straszak@cardinals.cc, Michal Swietek <michal.swietek@cardinals.cc>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/Cardinal-Cryptography/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.1.29"
hyper = "0.12.35"
jsonrpc-core-client = { version = "15.0.0", default-features = false, features = ["http"] }
log = "0.4.8"
sp-tracing = { version = "2.0.0", path = "../../../primitives/tracing" }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
sc-rpc = { version = "2.0.0", path = "../../../client/rpc" }
