[package]
name = "randomness-beacon"
version = "0.1.0"
authors = ["Michal Swietek <michael.swietek@alephzero.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
